# Creates a GitHub Release.
# Workflow is manually run.
# Preselect branch or tag before running this workflow.
name: github-release

on:
  workflow_dispatch:
    inputs:
      draft:
        description: "Create a release draft"
        required: false
        default: true
        type: boolean
      prerelease:
        description: "Mark this release as a prerelease"
        required: false
        default: false
        type: boolean
      generate-release-notes:
        description: "Generate the release notes automatically"
        required: true
        default: true
        type: boolean
      body:
        description: "Release notes to prepend"
        required: false
        type: string
      make-latest:
        description: "Latest release (Prereleases default false)"
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
          - legacy

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: openbao
          pattern: openbao*.zip
      - uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{ inputs.body }}
          draft: ${{ inputs.draft }}
          files: openbao/*
          generate_release_notes: ${{ inputs.generate-release-notes }}
          make_latest: ${{ inputs.make-latest }}
          prerelease: ${{ inputs.prerelease }}
